[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.6",
    "onnxruntime>=1.22.0",
    "pillow>=11.2.1",
    "rembg>=2.0.66",
    "streamlit>=1.45.1",
]
